# Generated by Django 4.0.3 on 2022-03-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('stripe_id', models.IntegerField()),
                ('sq_api_token', models.CharField(max_length=120)),
                ('sq_merchant_id', models.CharField(max_length=120)),
                ('sq_location_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=120)),
                ('invoice_id', models.CharField(max_length=120)),
                ('order_amount_fiat', models.FloatField(null=True)),
                ('crypto_amount_eth', models.FloatField(null=True)),
                ('crypto_txn_hash', models.CharField(max_length=120, null=True)),
                ('crypto_uid', models.CharField(max_length=120, null=True)),
                ('exchange_amount_fiat', models.FloatField(null=True)),
                ('exchange_sale_id', models.CharField(max_length=120, null=True)),
                ('plaid_access_token', models.CharField(max_length=120, null=True)),
                ('plaid_txn_id', models.CharField(max_length=120, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.merchant')),
            ],
        ),
    ]
