# Generated by Django 4.0.3 on 2022-03-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='sq_api_token',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='sq_location_id',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='sq_merchant_id',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
