# Generated by Django 4.0.3 on 2022-03-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_merchant_sq_api_token_merchant_sq_location_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=120)),
                ('invoice_id', models.CharField(max_length=120)),
                ('order_amount_fiat', models.FloatField()),
                ('crypto_amount_eth', models.FloatField()),
                ('crypto_txn_hash', models.CharField(max_length=120)),
                ('crypto_uid', models.IntegerField()),
                ('exchange_amount_fiat', models.FloatField()),
                ('exchange_sale_id', models.CharField(max_length=120)),
                ('plaid_access_token', models.CharField(max_length=120)),
                ('plaid_txn_id', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.merchant')),
            ],
        ),
    ]
